/**
 * Let us play a game of number guessing.
 * You will be asked for a number between 1 to 10. Once user will enter a number, you'll tell user if the entered number is lower or higher. with this information, user will change the number and finally guess the right number. You also need to show the number of attempts made by the user to reach to this right guess.
 **/

const guessTheNumber = (attempts = 0) => {
	console.log("*** Getting started with the Number guessing game ***");

	const userChoicePrompt = prompt("Enter a number between 1 and 10");

	const userChoice = Number(userChoicePrompt);

	let computerChoice;

	computerChoice = Math.floor(Math.random() * 10) + 1;
	const currentAttempt = attempts + 1;

	console.log(computerChoice);

	// if the user enters anything other than a number
	if (
		userChoicePrompt.trim() === "" ||
		userChoicePrompt === null ||
		Number.isNaN(userChoice)
	) {
		alert("You must enter a number");
		return;
	}

	// if the user enters numbers beyond 1 and 10
	if (userChoice > 10 || userChoice < 1) {
		alert("You must enter a number between 1 and 10");
		return;
	}

	// compare between user prompt and random number generated by JS
	if (computerChoice > userChoicePrompt) {
		console.log("You've selected a lower number");
	} else if (computerChoice < userChoicePrompt) {
		console.log("You've selected a higher number");
	} else {
		console.log(
			`You've guessed the correct number in ${currentAttempt} attempt(s)`,
		);
		return;
	}

	// play again prompt
	const playAgainPrompt = prompt("Do you want to play again(yes/no)");

	const playAgain = playAgainPrompt ? playAgainPrompt : "no";

	if (playAgain === "yes") {
		guessTheNumber(currentAttempt);
	} else {
		console.log("Thanks for playing, see you next time");
	}
};

guessTheNumber();
